#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Every path below is repository-relative, .env included, so anchor the
# wizard to the repository root rather than to wherever it was invoked.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# The version is read from the package so the tag cannot disagree with
# what the wheel will carry.
VERSION="$(sed -n 's/^__version__ = "\(.*\)"/\1/p' src/pippen/__init__.py)"
TAG="v$VERSION"

# Progress is recorded in .env, which is gitignored, so a run that stops after
# stage 2 can resume at stage 3 instead of repeating browser work.
done_already() { [[ "$(_existing "$1" 2>/dev/null || true)" == "done" ]]; }
mark_done()    { write_env "$1" "done" >/dev/null; }

skip_if_done() {
  local key="$1"
  done_already "$key" || return 1
  note "already recorded as done on a previous run"
  confirm "Do it again anyway?" && return 1
  return 0
}

banner "PIPPEN publishing setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "PyPI: configure Trusted Publishing"
if ! skip_if_done PIPPEN_SETUP_PYPI_PUBLISHER; then
  say "This lets GitHub Actions publish without any stored password."
  say "PyPI checks who is asking instead of what they know."
  printf '\n'
  warn "pippen 0.0.0 is already on PyPI, so use the EXISTING project form."
  note "The 'pending publisher' form is for names that do not exist yet."
  printf '\n'
  open_url "https://pypi.org/manage/project/pippen/settings/publishing/"
  step "Under 'Add a new publisher', choose GitHub."
  step "Fill in exactly these four values:"
  printf '\n'
  printf '      owner            %sAlphaNerdFx%s\n' "$BOLD" "$RESET"
  printf '      repository       %spippen%s\n'      "$BOLD" "$RESET"
  printf '      workflow name    %srelease.yml%s\n' "$BOLD" "$RESET"
  printf '      environment      %spypi%s\n'        "$BOLD" "$RESET"
  printf '\n'
  note "workflow name is the FILENAME, not the 'name:' written inside it"
  warn "Leaving environment blank lets ANY workflow in the repo publish,"
  warn "including one added by a pull request. Fill it in."
  printf '\n'
  step "Click 'Add'."
  pause "Press Enter once the publisher is listed."
  mark_done PIPPEN_SETUP_PYPI_PUBLISHER
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GitHub: create the 'pypi' environment"
if ! skip_if_done PIPPEN_SETUP_GH_ENVIRONMENT; then
  say "PyPI checks an 'environment' claim in the token GitHub mints."
  say "If the environment does not exist, the claim never matches."
  printf '\n'
  open_url "https://github.com/AlphaNerdFx/pippen/settings/environments"
  step "Click 'New environment'."
  step "Name it exactly: pypi"
  step "Click 'Configure environment'."
  printf '\n'
  say "Recommended: tick 'Required reviewers' and add yourself."
  note "That turns 'git push --tags' into a proposal you approve, rather"
  note "than an irreversible publish. A bad tag becomes a declined review."
  printf '\n'
  pause "Press Enter once the environment exists."
  mark_done PIPPEN_SETUP_GH_ENVIRONMENT
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "PyPI: revoke the stored token"
if ! skip_if_done PIPPEN_SETUP_TOKEN_REVOKED; then
  warn "This is the step that actually reduces risk, and the easiest to skip."
  say "Trusted Publishing is an additional way in, not a replacement."
  say "The old token stays valid until revoked, and a project with both"
  say "has the security of the weaker one."
  printf '\n'
  open_url "https://pypi.org/manage/account/token/"
  step "Find the token scoped to the pippen project."
  step "Click it, then 'Remove token', and confirm."
  pause "Press Enter once it is revoked on PyPI."
  printf '\n'
  if grep -qE '^PYPI_TOKEN=' "$ENV_FILE" 2>/dev/null; then
    say "PYPI_TOKEN is still present in $ENV_FILE."
    if confirm "Remove that line now?"; then
      tmp=$(mktemp)
      grep -vE '^PYPI_TOKEN=' "$ENV_FILE" > "$tmp" || true
      mv "$tmp" "$ENV_FILE"
      printf '  %s✓ removed%s PYPI_TOKEN from %s\n' "$GREEN" "$RESET" "$ENV_FILE"
    else
      warn "left in place; a revoked token is harmless but the habit is not"
    fi
  else
    note "no PYPI_TOKEN line in $ENV_FILE"
  fi
  mark_done PIPPEN_SETUP_TOKEN_REVOKED
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Zenodo: enable archiving for a citable DOI"
if ! skip_if_done PIPPEN_SETUP_ZENODO; then
  say "Zenodo watches the repository and archives each GitHub release,"
  say "minting a DOI that papers and other software can cite."
  printf '\n'
  warn "Zenodo only archives releases created AFTER the toggle is on."
  warn "Do this before tagging in stage 5, or $TAG gets no DOI."
  printf '\n'
  open_url "https://zenodo.org/account/settings/github/"
  step "Log in with GitHub and authorise Zenodo if asked."
  step "Find AlphaNerdFx/pippen in the repository list."
  step "Flip its toggle to ON."
  note "Click 'Sync now' if the repository is not listed yet."
  printf '\n'
  say "The repository already carries .zenodo.json and CITATION.cff,"
  say "so Zenodo takes its title, description and keywords from those."
  printf '\n'
  warn "CITATION.cff lists the author as the handle 'AlphaNerdFx'."
  warn "Replace it with your legal name before minting a DOI. A citation"
  warn "carrying a handle is hard to credit in academic work."
  printf '\n'
  pause "Press Enter once the toggle is on."
  mark_done PIPPEN_SETUP_ZENODO
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Release: tag $TAG"
if ! skip_if_done PIPPEN_SETUP_TAGGED; then
  branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
  say "Branch: $branch"

  # Zenodo mints the DOI against the date in CITATION.cff, so a stale date
  # there becomes a permanent part of the citation.
  dated=$(sed -n 's/^date-released: "\(.*\)"/\1/p' CITATION.cff)
  today=$(date +%F)
  if [[ "$dated" != "$today" ]]; then
    warn "CITATION.cff records date-released: $dated, and today is $today."
    warn "Update it and commit, then run this again."
    confirm "Tag with the date as it stands?" || { finish; exit 0; }
  fi
  if [[ "$branch" != main ]]; then
    warn "not on main. A detached HEAD reports itself as HEAD here."
    warn "The tag would carry whatever this branch holds."
    confirm "Tag from $branch anyway?" || { finish; exit 0; }
  fi

  if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
    warn "the working tree has uncommitted changes"
    git status --short | head -10
    printf '\n'
    say "Commit or stash them, then run this script again."
    finish
    exit 0
  fi
  note "working tree is clean"

  if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null 2>&1; then
    warn "tag $TAG already exists locally"
    say "Delete it first if you meant to recreate it:"
    note "  git tag -d $TAG && git push --delete origin $TAG"
    finish
    exit 0
  fi
  note "tag $TAG does not exist yet"

  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    note "gh is authenticated"
  else
    note "gh is unavailable or logged out, so the run cannot be watched here"
  fi

  printf '\n'
  say "Tagging triggers .github/workflows/release.yml, which builds the"
  say "wheel and sdist, publishes to PyPI through the publisher from"
  say "stage 1, and creates a GitHub release for Zenodo to archive."
  printf '\n'
  warn "A version published to PyPI can be deleted but never re-uploaded."
  warn "$VERSION is spent either way once this succeeds."
  printf '\n'

  if confirm "Tag $TAG and push it?"; then
    git tag -a "$TAG" -m "$TAG"
    git push origin "$TAG"
    printf '  %s✓ pushed%s tag %s\n' "$GREEN" "$RESET" "$TAG"
    mark_done PIPPEN_SETUP_TAGGED
    printf '\n'
    say "The release job runs now. A required reviewer on the pypi"
    say "environment holds it until you approve, so publication takes"
    say "anything from a minute to as long as you leave it waiting."
    printf '\n'
    if timeout 20 curl -fsS "https://pypi.org/pypi/pippen/json" 2>/dev/null \
       | grep -q "\"version\": *\"$VERSION\""; then
      printf '  %s✓ pippen %s is live on PyPI%s\n' "$GREEN" "$VERSION" "$RESET"
      open_url "https://pypi.org/project/pippen/$VERSION/"
    else
      note "$VERSION is not on PyPI yet, which is expected this soon."
      note "Watch the run, approve it if it is waiting, then reload the page."
      open_url "https://github.com/AlphaNerdFx/pippen/actions/workflows/release.yml"
    fi
  else
    say "Nothing tagged. Run this again when ready."
  fi
fi

finish
